# Generated by Django 6.1 on 2026-08-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="department",
            field=models.CharField(max_length=10),
        ),
    ]
